version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lead-manager-app
    container_name: app
    restart: unless-stopped
    ports:
       - "8000:8000"  # Port for debugging
       - "9000:9000"  # Port for PHP-FPM communication
    volumes:
      - ./:/var/www
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG="client_host=host.docker.internal"
    networks:
      - lead-manager-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
       - lead-manager-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
       - lead-manager-network

volumes:
  mysql-data:
    driver: local

networks:
   lead-manager-network:
    driver: bridge